### PR TITLE
Preserve case in render-uri for file:// URIs

### PR DESCRIPTION
**Pull request by Ambrevar**
Fixes https://github.com/atlas-engineer/nyxt/issues/974.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Friendly ping :)

**Comment by Ambrevar** [comment]
@fukamachi Anything blocking this merge?  Are you still maintaining this package?  Otherwise I'd be happy to maintain a fork, let me know :)

By the way, this can probably be closed in favor of #35.

**Comment by fukamachi** [comment]
@Ambrevar 
Thank you for these changes and your offer.

I'm busy and frequently suspend the maintenance of my libraries.
If you're okay, I'd be happy to delegate it to you.

**Comment by fukamachi** [comment]
Anyway, I merged changes of your fork into this repository.
I appreciate your effort :)

**Comment by fukamachi** [comment]
I'm ready to transfer this repository to you (or anywhere), but you have the fork which has the same name.
I think it'd be acceptable to change the repository of Quicklisp upstream, however, transfer might be better for someone who come to this URL because GitHub redirects them.

**Comment by Ambrevar** [comment]
Hi @fukamachi !
Thanks for the offer!

If you don't mind, I think it'd be more convenient if you give me commit
access to this repo.

It's less disruptive and it allows us to keep the issue tracker intact.

What do you think?

**Comment by fukamachi** [comment]
I respect your opinion as a new maintainer :)
I invited you to this repo.

**Comment by Ambrevar** [comment]
Thank you very much!

**Pull request merged**
