### PR TITLE
Export all URI constructors.

### PR DESCRIPTION
**Pull request by Ambrevar**
@aadcg @aartaka Makes sense?

### CODE REVIEW

**Comment by aartaka** [comment]
Yes!

**Comment by aadcg** [comment]
Absolutely. There's also `make-basic-uri`, but perhaps it doesn't make sense to export.

**Comment by aadcg** [comment]
To have more control, especially when defining URLs that have non-standard schemes. Example: you can't set the URL's path to the empty string via `quri:uri "a-string"`.

**Comment by aartaka** [comment]
> To have more control, especially when defining URLs that have non-standard schemes. Example: you can't set the URL's path to the empty string via `quri:uri "a-string"`.

You can: `(quri:uri "a-scheme:")` :P

**Comment by aadcg** [comment]
Not quite. Find a screenshot below.

**Pull request merged**
